# @name index
GET http://localhost:{{$dotenv APP_PORT}}

###

# @name health
GET http://localhost:{{$dotenv APP_PORT}}/health

###

# @name create-user
POST http://localhost:{{$dotenv APP_PORT}}/users
Content-Type: application/json

{
  "age": 21,
  "email": "test@example.com",
  "name": "Gabriel Santos Cardoso",
  "nickname": "gabe",
  "password": "Secret123456@"
}

###

# @name list-users
GET http://localhost:{{$dotenv APP_PORT}}/users

###

# @name show-user
GET http://localhost:{{$dotenv APP_PORT}}/users/1

###

# @name update-user
PATCH http://localhost:{{$dotenv APP_PORT}}/users/1
Content-Type: application/json

{
  "age": 21,
  "email": "test@example.com",
  "name": "Gabriel Santos Cardoso",
  "nickname": "gabe_dev",
  "password": "Secret123456@"
}

###

# @name delete-user
DELETE http://localhost:{{$dotenv APP_PORT}}/users/1

###
